### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by LifeGold** [Virtual-Universe/Virtual-Dev#31] opened 2016-11-14 19:50 UTC
Hi all. I wanted to ask, is it possible to make the name in the inventory of things, folders, objects in Russian?
http://prntscr.com/d79vdq

**Comment by emperorstarfinder** [comment] 2016-11-14 20:14
You can rename the inventory item by simply right clicking and selecting rename and then replace the name with the russian version.  However there is no guarantee that this will work and might actually break the inventory.  It is something we are working on hopefully to be implemented in Release Version 1.0.3 but no promises.

Emperor Starfinder
Founder
Chief Executive Officer
Core Developer
Governing Body Chair
Grid Architecture Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team
Email: emperor@secondgalaxy.com

**Comment by LifeGold** [comment] 2016-11-14 20:17
@emperorstarfinder What's the problem, not working Russian language, it then displays the name in the format D2 B5 B7 B9

**Comment by emperorstarfinder** [comment] 2016-11-14 20:24
We are aware of that issue.  

Unfortunately it is likely being caused by the locale stuff within the server's operating system for the Russian language.  This is partly due to the format and font used for the Russian language.

Our Core Developers are trying to sort this out but it might take some time for us to resolve.  

For the moment, if naming inventory items in Russian is causing issues, I would encourage and recommend you leave the default English version of the names for now while we sort this out.  This way you can ensure the inventory for your users wont break.  

Emperor Starfinder
Founder
Chief Executive Officer
Core Developer
Governing Body Chair
Grid Architecture Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team
Email: emperor@secondgalaxy.com

**Comment by LifeGold** [comment] 2016-11-14 20:58
@emperorstarfinder Thank you I hope a solution will find as our users, it is very difficult when everything is in English. And not all know English.

**Comment by emperorstarfinder** [comment] 2016-11-14 21:49
Question has been answered so closing

Emperor Starfinder
Founder
Chief Executive Officer
Core Developer
Governing Body Chair
Grid Architecture Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team
Email: emperor@secondgalaxy.com

**Closed by emperorstarfinder** 2016-11-14 21:49 UTC
Labels: question
