### ISSUE TITLE
Error Base HTTP server

### ISSUE THREAD

**Issue by LifeGold** [Virtual-Universe/Virtual-Dev#28] opened 2016-09-18 17:12 UTC
[Base HTTP server]: HandleRequest() threw System.Net.HttpListenerException (0x80004005): Операция ввода/вывода была прервана из-за завершения потока команд или по запросу приложения
   в System.Net.HttpRequestStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   в Universe.Framework.Servers.HttpServer.HttpServerHandlerHelpers.ReadString(Stream stream) в d:\Virtual-Dev-master\Universe\Framework\Servers\HttpServer\Http Methods\GenericStreamHandler.cs:строка 104
   в Universe.Framework.Services.ServerHandler.Handle(String path, Stream requestData, OSHttpRequest httpRequest, OSHttpResponse httpResponse) в d:\Virtual-Dev-master\Universe\Framework\Services\ConnectorBase.cs:строка 399
   в Universe.Framework.Servers.HttpServer.BaseHttpServer.HandleRequest(HttpListenerContext context) в d:\Virtual-Dev-master\Universe\Framework\Servers\HttpServer\BaseHttpServer.cs:строка 387 

**Operating system**: Windows Server 2012 AND Ubuntu 14.04

**Comment by emperorstarfinder** [comment] 2016-09-18 18:11
Is this in the grid or region server?

**Comment by WhiteCoreWebUI** [comment] 2016-09-18 18:16
This seems to be related to the private osdmap GiveUserObject

**Comment by ThunderLife** [comment] 2016-09-18 18:18
This seems to be related to a SendUserObject in the phpwebui but this was already removed a while ago

**Comment by ThunderLife** [comment] 2016-09-18 18:25
Also please @LifeGold please tell us how to reproduce this error

**Comment by LifeGold** [comment] 2016-09-18 18:36
@emperorstarfinder It was so. Removed all servers and databases. Once you have downloaded the newest, compiled it and ran it, put on avatar and went to the regions, this error in the region server. I look after what action this happens.

**Comment by LifeGold** [comment] 2016-09-18 18:36
@ThunderLife  @emperorstarfinder  It was so. Removed all servers and databases. Once you have downloaded the newest, compiled it and ran it, put on avatar and went to the regions, this error in the region server. I look after what action this happens.

**Comment by emperorstarfinder** [comment] 2016-09-18 18:40
Can you tell us what your doing when the error comes up?

**Comment by ThunderLife** [comment] 2016-09-18 18:42
Also does this error come in Universe.exe or Universe.Server.exe

**Comment by LifeGold** [comment] 2016-09-18 18:46
@ThunderLife Universe.Server.exe @emperorstarfinder  Let me see what it is. Several times he was can not now repeat it.

**Comment by emperorstarfinder** [comment] 2016-09-18 18:48
Okay if you look at the log around the time it happens that should help

**Comment by LifeGold** [comment] 2016-09-18 19:11
@emperorstarfinder When you run compile on Ubuntu 14.04  http://prntscr.com/cjiz00

**Comment by emperorstarfinder** [comment] 2016-09-18 19:18
no need to do sudo when doing the ./runprebuild.sh command

**Comment by ThunderLife** [comment] 2016-09-18 19:24
and if you insist on using sudo do it like

sudo bash runprebuilt.sh

**Comment by LifeGold** [comment] 2016-09-18 19:34
@emperorstarfinder http://prntscr.com/cjja3y

**Comment by emperorstarfinder** [comment] 2016-09-18 19:35
technically if your running the prebuild.sh in sudo or even the grid and region server in sudo you will potentially cause unnecessary problems.  As long as your not putting Virtual Universe in a directory that is considered a system directory and leave it in the Home directory sudo should not ever be needed

**Comment by LifeGold** [comment] 2016-09-18 19:39
@emperorstarfinder   What is interesting is that there's more than one error http://prntscr.com/cjjcjb

**Comment by emperorstarfinder** [comment] 2016-09-18 19:39
Pull from latest master now and build should be fine.

**Comment by LifeGold** [comment] 2016-09-18 19:45
@emperorstarfinder Work.  There was a warning when creating the region. http://prntscr.com/cjjf7x

**Comment by emperorstarfinder** [comment] 2016-09-18 19:47
That is a warning but in fact its really not a bug as all region textures appear normally but we are aware of that particular error.

**Comment by LifeGold** [comment] 2016-09-19 05:57
@emperorstarfinder Hi this is the error writes when the server shuts down http://prntscr.com/cjoe2i

**Comment by emperorstarfinder** [comment] 2016-09-19 09:41
Okay that just basically means something is caught in process while terminating as long as your shutting your region server down first and letting a minute or so pass before shutting the grid server down you should be ok.  Its an error but not really a major issue but one we definately will need to address.

**Comment by LifeGold** [comment] 2016-09-19 12:48
@emperorstarfinder Error connecting to region. http://prntscr.com/cjsivo

**Comment by CaseyraeStarfinder** [comment] 2016-11-07 04:15
Closing as user has reported no further issues and this appears to have been corrected in a recent commit.

Best Regards,
Caseyrae Starfinder
Governing Body Vice Chair (Europe)
Core Developer
Viewer Developer Work Group Leader
Viewer Development Work Group
Second Galaxy Development Team
Email: caseyrae@secondgalaxy.com

**Closed by CaseyraeStarfinder** 2016-11-07 04:15 UTC
Labels: bug, Need More Information From User, On Hold
