### ISSUE TITLE
The server crash on Ubuntu

### ISSUE THREAD

**Issue by LifeGold** [Virtual-Universe/Virtual-Dev#30] opened 2016-09-22 18:41 UTC
### Steps to reproduce

1.  The server crash on Ubuntu. On Windows works without error. What this error is not clear. The user can simply log in and the server crashes, and can use the editor. It every time different.

http://prnt.sc/cl58no
http://prntscr.com/cl5cp9
### Server configuration

**Operating system**: Ubuntu 14.04

**Comment by DevilStarfinder** [comment] 2016-09-22 21:24
How much memory does your machine run with?

**Comment by LifeGold** [comment] 2016-09-22 21:45
Server configuration Dual Intel® Xeon® Processor Quad Core L5520 / 96 GB DDR / HDD 2Tb 5400 rpm Sata3 2.5 / OS Ubuntu 14.04 LTS (64 bit)

**Comment by DevilStarfinder** [comment] 2016-09-22 21:47
okay please post mono -V and post the output

**Comment by LifeGold** [comment] 2016-09-22 21:48
@DevilStarfinder  Mono JIT compiler version 4.4.1 (Nightly 4.4.1.0/4747417 Wed Jun 22 11:14:49 UTC 2016)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen

**Comment by DevilStarfinder** [comment] 2016-09-22 21:49
please use the lates stable version of mono, the nightly i known to be buggy

**Comment by LifeGold** [comment] 2016-09-22 21:51
@DevilStarfinder Another How to put you will not prompt?

**Comment by DevilStarfinder** [comment] 2016-09-22 21:52
the crash you are experiencing is most likely due to your mono version the nightly is a higly unstable version of mono the last stable is Mono JIT compiler version 4.6.0 , so first of you are using a outdated version second a buggy one

**Comment by QueenStarfinder** [comment] 2016-09-22 23:33
Hi there,

The reason you are seeing this error is not one caused by Virtual Universe itself, rather it is actually caused by the memory being low on your server.  

It should be noted that the Unity Desktop which is the default in the Ubuntu Desktop operating system takes up approximately 1/2 to 2/3 of your operating system's allocated memory.  The temporary solution would be to just reboot the server.

When running a grid on Linux it is usually better to run the server version of Ubuntu, Debian, Arch, Fedora, openSUSE, etc.  However if you need to use a desktop environment in Linux, then I would recommend either XUbuntu x64 because it uses the XFCE desktop environment which takes up less space and resources in the Ubuntu Dstribution Flavour.  There is also Manjaro which Virtual Universe does in fact work on to and it is nice and fast.  Debian also provides a desktop operating system environment as well which works similar to Ubuntu and is stable and fast.

Mono - We never encourage grid operators to use a nightly build of mono as this is known to cause problems which are not problems we would generally see.  Always use the latest stable version of mono.  The latest stable version is 4.6.0 it will work just fine with Virtual Universe.

While this is not a bug caused by Virtual Universe directly, I will leave this issue open in case this becomes a persistant problem for you.  However I would also recommend upgrading Ubuntu if you plan to stay with Ubuntu.

Queen Starfinder
Core Developer
Physics Engine Developer
Work Group Member
Grid Architecture Development Work Group
Viewer Development Work Group
Second Galaxy Development Team

**Comment by DevilStarfinder** [comment] 2016-09-22 23:34
@QueenStarfinder mine and @emperorstarfinder Words

**Comment by emperorstarfinder** [comment] 2016-09-27 14:50
Closing as this appears to be an issue with Mono not caused by Virtual Universe.

If problem persists then please by all means open a new issue.

Emperor Starfinder
CEO/ Founder
Core Developer
Grid Architecture Development
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Closed by emperorstarfinder** 2016-09-27 14:50 UTC
Labels: bug
